### ISSUE TITLE
should we move to JSCS from eslint?

### ISSUE THREAD

**Issue by ochanje210** [sv-bootcamp/Pingo#65]

**Comment by ochanje210** [comment]
It has auto-fix functionality in WebStorm text editor while eslint does not

**Comment by festinalente91** [comment]
it is fine choice if we all decide to use web storm.

**Comment by ochanje210** [comment]
so auto-fix feature only exists in webstorm?

**Comment by festinalente91** [comment]
but I prefer to manually doing it. Because you can get ised to the right syntax and plus it is not that hard after you get used to it.

**Comment by ochanje210** [comment]
it is true. it's been a good practice indeed.
